### ISSUE TITLE
[doubt] How to use the module?

### ISSUE THREAD

**Issue by miusei** [Ridiculosity-Games/trapped-doors#2] opened 2022-12-29 14:14 UTC
Hi good afternoon, I really liked the module but I'm having some difficulties creating traps (pf2e), attach to the door and create a key for the locked doors... sorry to bother you with these doubts

**Comment by KMoney5** [comment] 2022-12-29 16:58
Are you using Foundry v9? It looks like I may have broken compatibility with the v10 upgrade.

**Comment by miusei** [comment] 2022-12-29 17:01
i using v10

**Comment by miusei** [comment] 2022-12-29 17:02
maybe I'm using the module wrong since I didn't find any menu or option to use the functions

**Comment by KMoney5** [comment] 2022-12-29 17:15
You should definitely at least be seeing module settings in the game settings menu - but it looks like I need to figure out a better way to support systems other than 5e. I'll put together a release later today to fix this issue, the problem is I'm specifically looking for a 5e compendium, which wouldn't get created for a pf2e game on module install.

**Comment by KMoney5** [comment] 2022-12-29 17:22
For now, if you'd like to fix this locally, add the following to module.json, under the dnd5e trap pack, and then restart Foundry:
```
,
    {
      "name": "td-traps",
      "label": "Traps (Trapped Doors)",
      "path": "packs/td-pf2etraps.db",
      "system": "pf2e",
      "type": "Actor",
      "private": false,
      "flags": {}
    }
```
It should look like this:
![image](https://user-images.githubusercontent.com/110709343/209987538-0576d21d-edd1-45dd-b541-f10bb231f083.png)

**Comment by miusei** [comment] 2022-12-29 18:36
![image](https://user-images.githubusercontent.com/98015429/209994563-60e7ae6e-568c-4a54-bce9-88cf9b4e35e2.png)

PF2E

I added the code and the traps folder was imported (empty and the key folder did not appear), I added the trap in the configuration but when trying to open the door it does not open and the following error appears in the console.

DND5e.

Both folders appear normally and with the content, I add the trap, I try to open the door but it does not open and the same error appears in the console,

-V10
-Only trapped door activated
-system: pf2e and dnd5e

**Comment by miusei** [comment] 2022-12-29 18:56
![image](https://user-images.githubusercontent.com/98015429/209996807-3a09c6a1-33a6-4346-afd9-d9c4b1f660f9.png)
dnd 5e error

**Comment by KMoney5** [comment] 2022-12-29 18:57
It looks like the socket isnt getting initialized, do you have socketlib installed as well? I might have missed something with the dependencies to make it not get pulled in, but installing it should fix that. As for the key, you should be able to make a similar change in the module.json:

```
 ,
  {
      "name": "td-items",
      "label": "Items (Trapped Doors)",
      "path": "packs/td-pf2eitems.db",
      "system": "pf2e",
      "type": "Item",
      "private": false,
      "flags": {}
    }
```
And you would have to add an item named "Key" to it. I'll make sure to fix that as well in the release.

For making your own traps for pf2e, look at the ones included in the 5e pack. It specifically looks for an "Effect" action to roll when triggering the trap.

**Comment by miusei** [comment] 2022-12-29 19:40
now everything is working perfectly, thanks a lot for the help

**Comment by miusei** [comment] 2022-12-29 20:37
![image](https://user-images.githubusercontent.com/98015429/210008236-b45b8bcf-60ad-4e45-9cf9-671117686d30.png)
![image](https://user-images.githubusercontent.com/98015429/210008786-bc197937-b30b-4a7e-ba49-06e86a1da0bc.png)
whenever I try to run the trap configured in PF2e the sheet is cloned and returns this error.

I Tried:

-NPC sheet
-Hazard sheet
-Player sheet

**Comment by KMoney5** [comment] 2022-12-30 06:24
A new version is up that should fix most of your issues - there is now an example trap in the pf2e compendium as well. I still have to fix the dependency on socketlib, and I also need to automate one more thing - you'll need to add a "Door Traps" Actors folder, as it tries to move the actors into that folder as of right now to try to keep things clean, and it doesn't create it for you automatically.

**Comment by miusei** [comment] 2022-12-30 17:10
thank you very much, your module is amazing

**Comment by ZhornLegacy** [comment] 2022-12-31 16:07
I like what you are building and look forward to seeing the further progress on this.

But this module could use a short wiki to explain the setup.
- Noting supported/intended systems on your landing page.
- If traps should be imported to the Door Trap folder first, or if it defaults to the compendium.
- how to add new traps (or if it is not yet intended)
etc

Using 5e, so I understand that it's not currently configured fully yet (please don't view this as criticism, just listing things as I see them).
Stumbling through it was running into an issues with the traps attempting to load from the compendium with 0 hp thus getting an incapacitated issue (no rolls to chat, no application of the trap, etc)
![image](https://user-images.githubusercontent.com/106674701/210148741-82bbc5e0-b29e-4f36-8ff6-3760ce7a2523.png)

Once traps have been manually imported (the auto import/delete has a whole slew of numerical errors) they can be configured to do as they say in the box text says. Attributes set to 0(-5) rather than 10(+0) and not accounting for the proficiency bonus; throws many of the attack rolls out.

Again, I like where this is going. Early and rough, but promising.

**Comment by KMoney5** [comment] 2022-12-31 17:12
Thank you for the feedback - I think what you’re seeing is interactions with other modules, as I haven’t had any problems running the traps in 5e personally. Either way, definitely things I want to fix, so thank you for bringing it to my attention.

Now that more than just me and my friends are using the module, a wiki is definitely on the roadmap, as it can definitely be a bit confusing. But for the traps in the compendium, you don’t need to pull them out manually. They should be generated into Actors when the trap is tripped and stuffed in the Door Traps folder for safekeeping. After (I think) five minutes, they then get deleted. Adding new traps is definitely supported! I tried to keep only the relevant information on the traps so that new ones could have an easy reference, but you should see for 5e traps there’s an “Effect” that they all have, that’s where they get rolled from. Once you make a new trap, just put it into the Traps compendium and it should start appearing in the wall config.

As far as compatibility goes, traps and keys are currently supported in pf2e and dnd5e, but the rest of the functionality (pausing on open, peeking) should work for all systems.

Edit: I just pulled up my 5e world again and I am seeing the rolls wrong now - maybe that's a difference between v9 and v10, because I know I was getting the right numbers when we were running my big trap dungeon on v9. The rolls were intended to take just the modifier I was giving them (+6 for crossbow trap, for example), but now that they're pulling in proficiency and stat mod, I definitely need to fix them. Thank you again.

**Comment by KMoney5** [comment] 2023-01-01 21:43
With the release of 1.1.3, I believe these issues should all be resolved, so I’m closing this issue. If you think there’s anything I need to add to the readme, or if you’re still getting errors in the console, please let me know what they are and what modules you have installed. I’m not 100% certain how pack updates work, so you may need to delete your trap compendium to pull in the changes to the traps (HP and stats). Thank you again!

**Closed as completed by KMoney5** 2023-01-01 21:43 UTC
